name: Custom Work Flow

on:
  release:
    types: [created]  
    
  workflow_dispatch:
 
jobs:
  generate_release_notes:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Generate Release Notes
        run: |
          echo "Generating Release Notes..."
         
