name: Custom Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch: 

  
jobs:
  custom_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom script
        run: |
          echo "Running custom script..."

      - name: Perform additional task
        uses: some-action/some-action@v1
        with:
          option: value
